name: Auto PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to main
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          source_branch: dev
          target_branch: main
          title: '🚀 Auto PR: Sync dev → main'
          body: |
            This PR was created automatically from a push to the `dev` branch.
            Please review and merge when ready.
