name: Auto Merge dev into main

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 PM UTC = 12:30 AM IST
  workflow_dispatch:       # Optional: allows manual runs from the GitHub UI

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        run: |
          git fetch origin dev
          git merge origin/dev --no-ff --commit -m "🔄 Scheduled auto-merge dev into main"
          git push origin main
