name: Convert and Compress Images

on:
  push:
    paths:
      - '**/*.png'

jobs:
  convert-and-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert PNG to JPG and delete PNGs
        run: |
          find . -type f -name "*.png" -print0 | while IFS= read -r -d '' img; do
            new_img="${img%.png}.jpg"
            convert "$img" "$new_img" && rm "$img"
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install imagemin-cli and plugins
        run: |
          npm install -g imagemin-cli imagemin-mozjpeg

      - name: Compress JPG and JPEG images
        run: |
          mkdir -p compressed
          npx imagemin "**/*.{jpg,jpeg}" --plugin=mozjpeg --out-dir=compressed
          rsync -a compressed/ ./
          rm -r compressed

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add .
          git diff --staged --quiet || git commit -m "Convert PNGs to JPGs and compress images"
          git push
