name: Auto Merge main into dev

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push to dev branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # Important for merging between branches

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge main into dev
        run: |
          git fetch origin main
          git merge origin/main --no-ff --commit -m "🔄 Auto-merged main into dev"
          git push origin dev
