name: Merge PDFs

on:
  push:
    paths:
      - '**.pdf'

jobs:
  merge-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pdftk  # or use pdf-merge if you prefer

      - name: Merge PDFs
        run: |
          mkdir merged_pdfs
          pdftk *.pdf cat output merged_pdfs/merged.pdf  # Merge all PDFs in the repo

      - name: Commit and push merged PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add merged_pdfs/merged.pdf
          git commit -m "Merged PDFs" || echo "No changes to commit"
          git push
